### ISSUE TITLE
##May I ask where the data set is configured specifically?

### ISSUE THREAD

**Issue by btqx** [mahdizynali/UNet-Brain-Tumor-Detection#1]
##May I ask where the data set is configured specifically?

**Comment by mahdizynali** [comment]
Hi.
try to download dataset from kaggle :
`https://www.kaggle.com/datasets/mateuszbuda/lgg-mri-segmentation/download?datasetVersionNumber=2`
then extract and move dataset file into base dir of program or may you wanna change readable path of dataset inside config.py :
`dataSets = file_path + "dataSets/*"`
have a nice time !
